# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trevalone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trevalone
  #AWSSDK

  pod 'AWSCloudWatch'
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSDynamoDB'
  pod 'AWSLambda'
  pod 'AWSMobileAnalytics'
  pod 'AWSS3'
  pod 'AWSSES'
  pod 'AWSSNS'

  #GoogleSDK
  
  pod 'GoogleSignIn', '~> 4.4'	

  #FacebookSDK

  pod 'FBSDKCoreKit' 
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  #SpringAnimation

  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

end
